#!/usr/bin/env python

# cluster.py - given a directory of plain text files as well as type of visualization, cluster a set of documents
# see --> https://de.dariah.eu/tatom/working_with_text.html

# Eric Lease Morgan <emorgan@nd.edu>
# October  17, 2017 - first cut; cool, again!
# February 15, 2020 - moving to workbook

# Usage: rdr cluster <carrel> <dendrogram|cube>
# Summary: Visualize the clusters of a carrel
# Help: Use this command to see how items in a study carrel may be similar or different

pass

# configure
MAXIMUM   = 0.95
MINIMUM   = 2
STOPWORDS = 'english'
EXTENSION = '.txt'

# require
from mpl_toolkits.mplot3d import Axes3D
from scipy.cluster.hierarchy import ward, dendrogram
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import MDS
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import os
import sys

# initialize
home      = os.getenv('_RDR_ROOT')
DIRECTORY = home + '/library/'

# sanity check
if len( sys.argv ) != 3 :
	os.system( 'rdr help cluster' )
	quit()

# get input
carrel        = sys.argv[ 1 ]
visualization = sys.argv[ 2 ]

# initialize & compute
directory  = DIRECTORY + carrel + "/txt"
filenames  = [ os.path.join( directory, filename ) for filename in os.listdir( directory ) ]
vectorizer = TfidfVectorizer( input='filename', max_df=MAXIMUM, min_df=MINIMUM, stop_words=STOPWORDS )
matrix     = vectorizer.fit_transform( filenames ).toarray()
distance   = 1 - cosine_similarity( matrix )
keys       = [ os.path.basename( filename ).replace( EXTENSION, '' ) for filename in filenames ] 

# branch according to configuration; visualize
if visualization == 'dendrogram' :
	linkage_matrix = ward( distance )
	dendrogram( linkage_matrix, orientation="right", labels=keys )
	plt.tight_layout() 

elif visualization == 'cube' :
	mds = MDS( n_components=3, dissimilarity="precomputed", random_state=1 )
	pos = mds.fit_transform( distance )
	fig = plt.figure()
	ax  = fig.add_subplot( 111, projection='3d' )
	ax.scatter( pos[ :, 0 ], pos[ :, 1 ], pos[ :, 2 ] )
	for x, y, z, s in zip( pos[ :, 0 ], pos[ :, 1 ], pos[ :, 2 ], keys ) : ax.text( x, y, z, s )

# error
else :
	os.system( 'rdr help cluster' )
	quit()

# output and done
plt.show()
exit()



